name: CD

on:
  push:
    tags: '*'

permissions:
  contents: read

jobs:
  build-lin:
    name: Linux Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-10-multilib
      - name: Build
        env:
          RELEASE_BUILD: 1
          DEMO_SIGN_PUBKEY: ${{ secrets.P2SM_DEMO_SIGN_PUBKEY }}
          DEMO_SIGN_PRIVKEY: ${{ secrets.P2SM_DEMO_SIGN_PRIVKEY }}
        run: make -j$(nproc)
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: p2sm-linux
          path: p2sm.so
          if-no-files-found: error
      - name: Upload to dl.p2sm.portal2.sr
        if: github.repository_owner == 'p2sr'
        env:
          DL_P2SM_API_TOKEN: ${{ secrets.DL_P2SM_API_TOKEN }}
        run: |
          P2SM_VERSION=$(git describe --tags)
          curl -X "POST" \
            -H "Authorization: Bearer $DL_P2SM_API_TOKEN" \
            -H "Content-Type: multipart/form-data" \
            -F "version=$(echo $P2SM_VERSION | awk -F- '{print $1}')" \
            -F "p2sm_version=$P2SM_VERSION" \
            -F "system=linux" \
            -F "commit=$GITHUB_SHA" \
            -F "branch=$GITHUB_REF_NAME" \
            -F "count=1" \
            -F "hashes[0]=$(sha256sum p2sm.so | cut -d ' ' -f 1)" \
            -F "files[0]=@p2sm.so" \
            "https://dl.p2sm.portal2.jonesy.moe/api/v1/upload"
  build-win:
    name: Windows Build
    runs-on: windows-2019
    permissions:
      contents: write
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Build
        env:
          RELEASE_BUILD: 1
          DEMO_SIGN_PUBKEY: ${{ secrets.P2SM_DEMO_SIGN_PUBKEY }}
          DEMO_SIGN_PRIVKEY: ${{ secrets.P2SM_DEMO_SIGN_PRIVKEY }}
        run: msbuild -m -t:SourceAutoRecord -p:"Configuration=Release;Platform=x86" SourceAutoRecord.sln
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: p2sm-windows
          path: bin\p2sm.dll
          if-no-files-found: error
      - name: Upload PDB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: p2sm-windows-pdb
          path: bin\p2sm.pdb
          if-no-files-found: error
      - name: Upload to dl.p2sm.portal2.sr
        if: github.repository_owner == 'p2sr'
        shell: bash
        env:
          DL_P2SM_API_TOKEN: ${{ secrets.DL_P2SM_API_TOKEN }}
        run: |
          P2SM_VERSION=$(git describe --tags)
          curl -X "POST" \
            -H "Authorization: Bearer $DL_P2SM_API_TOKEN" \
            -H "Content-Type: multipart/form-data" \
            -F "version=$(echo $P2SM_VERSION | awk -F- '{print $1}')" \
            -F "p2sm_version=$P2SM_VERSION" \
            -F "system=windows" \
            -F "commit=$GITHUB_SHA" \
            -F "branch=$GITHUB_REF_NAME" \
            -F "count=2" \
            -F "hashes[0]=$(sha256sum bin/p2sm.dll | cut -d ' ' -f 1)" \
            -F "hashes[1]=$(sha256sum bin/p2sm.pdb | cut -d ' ' -f 1)" \
            -F "files[0]=@bin/p2sm.dll" \
            -F "files[1]=@bin/p2sm.pdb" \
            "https://dl.p2sm.portal2.jonesy.moe/api/v1/upload"
  release:
    name: Release
    if: github.repository == 'p2sr/SourceAutoRecord'
    needs: [build-lin, build-win]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get Release Version
        id: get_release
        run: echo "version=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Download Linux Build
        uses: actions/download-artifact@v4
        with:
          name: p2sm-linux
      - name: Download Windows Build
        uses: actions/download-artifact@v4
        with:
          name: p2sm-windows
      - name: Download Windows PDB
        uses: actions/download-artifact@v4
        with:
          name: p2sm-windows-pdb
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            ![CD](https://github.com/p2sr/SourceAutoRecord/workflows/CD/badge.svg)

            **Installation**
            - Download:
              - [Windows](https://github.com/p2sr/SourceAutoRecord/releases/download/${{ env.version }}/p2sm.dll)
              - [Linux](https://github.com/p2sr/SourceAutoRecord/releases/download/${{ env.version }}/p2sm.so)
            - Place the binary into the game folder e.g. `Portal 2`
            - Open developer console and enter `plugin_load p2sm`

            ---

            **Changelog**
            TODO
          files: |
            p2sm.so
            p2sm.dll
            p2sm.pdb
          prerelease: ${{ contains(github.ref, '-pre') }}
          fail_on_unmatched_files: true
